### ISSUE TITLE
Problems with console.

### ISSUE THREAD

**Issue by NatsuTheGreat** [CigarProject/Cigar#107]
[Cigar] An open source Agar.io server implementation
module.js:340
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\elina\Downloads\Cigar-master\Cigar-master\server\web\app.js:1:77)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

C:\Users\elina\Downloads\Cigar-master\Cigar-master\server>pause
Press any key to continue . . .

How do I fix this in the console. Please help.

**Comment by m-byte** [comment]
It's all described in the readme ;)
https://github.com/CigarProject/Cigar#obtaining-and-using

**Comment by MastaCoder** [comment]
I made a install_dependencies.bat file if you want to put it on your Cigar server :)

**Comment by MastaCoder** [comment]
Added to Cigar!
