### ISSUE TITLE
Error Master Connect

### ISSUE THREAD

**Issue by Roken120** [CigarProject/Cigar#200]
Hello when I make an order on the master server's made me an error 
when add bot 
<2>addbot 4
<2>
undefined:1
[Game:2] Added 4 player bots
^
SyntaxError: Unexpected token
    at Object.parse (native)
    at WebSocket.<anonymous> (/root/Cigar/server/MasterServer.js:196:48)
    at WebSocket.emit (events.js:117:20)
    at Receiver.ontext (/root/Cigar/server/node_modules/ws/lib/WebSocket.js:797:10)
    at /root/Cigar/server/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/root/Cigar/server/node_modules/ws/lib/Receiver.js:360:5)
    at /root/Cigar/server/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/root/Cigar/server/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.1.finish (/root/Cigar/server/node_modules/ws/lib/Receiver.js:478:12)
    at Receiver.expectHandler (/root/Cigar/server/node_modules/ws/lib/Receiver.js:453:31)
-------------------------------------------------------

**Comment by mayed505** [comment]
Reinstall Cigar server folder. or replace it with a new onw should fix the problem.

**Comment by MastaCoder** [comment]
^
