### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by HEROx29** [CigarProject/Cigar#221]
root@^_^:~/Cigar# sh start_masterserver.sh
[BATCH] Debian detected. Using nodejs instead of node...
[BATCH] Starting Server with MasterServer

/root/Cigar/server/ai/BotLoader.js:43
    } catch (e) {
      ^^^^^
SyntaxError: Unexpected token catch
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/Cigar/server/GameServer.js:13:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by mys** [comment]
fix https://github.com/CigarProject/Cigar/pull/226
