### ISSUE TITLE
ban [IP] command is broken.

### ISSUE THREAD

**Issue by darknight99x** [CigarProject/Cigar#291]
Cannot ban user's IPs.

doing `ban [IP]` causes this error.

`readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'indexOf' of undefined
    at Commands.list.ban (C:\Users\Root\Desktop\agarprivate.ml\server\modules\CommandList.js:49:30)
    at parseCommands (C:\Users\Root\Desktop\agarprivate.ml\server\index.js:117:9)
    at C:\Users\Root\Desktop\agarprivate.ml\server\index.js:95:9
    at Interface._onLine (readline.js:209:5)
    at Interface._line (readline.js:550:8)
    at Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKeys (readline.js:1251:14)

---

[BATCH] Server Shutdown, waiting 15 seconds before a restart.

`

**Comment by MastaCoder** [comment]
I'll look into it if I ever have time :(

**Comment by tveloper** [comment]
You haven't added the square brackets [ ] when entering IP address, right?

`ban 192.168.1.1` is the correct form, 
NOT `ban [192.168.1.1]`

**Comment by darknight99x** [comment]
@tveloper I do the correct form you say and it still crashes my server.

**Comment by MastaCoder** [comment]
Cigar is now client only.
