### ISSUE TITLE
Random ERROR that keeps appearing with no significant intervals.

### ISSUE THREAD

**Issue by darknight99x** [CigarProject/Cigar#299]
Keeps happening at random for no reason.

C:\Users\Root\Desktop\agarprivate.ml\server\PacketHandler.js:44
                var charCode = view.getUint16(i, true);
                                    ^

RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint16 (native)
    at PacketHandler.handleMessage (C:\Users\Root\Desktop\agarprivate.ml\server\PacketHandler.js:44:37)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\Root\Desktop\agarprivate.ml\server\node_modules\ws\lib\WebSocket.js:804:10)
    at C:\Users\Root\Desktop\agarprivate.ml\server\node_modules\ws\lib\Receiver.js:533:18
    at Receiver.applyExtensions (C:\Users\Root\Desktop\agarprivate.ml\server\node_modules\ws\lib\Receiver.js:360:5)
    at C:\Users\Root\Desktop\agarprivate.ml\server\node_modules\ws\lib\Receiver.js:527:14
    at Receiver.flush (C:\Users\Root\Desktop\agarprivate.ml\server\node_modules\ws\lib\Receiver.js:336:3)
    at Receiver.opcodes.2.finish (C:\Users\Root\Desktop\agarprivate.ml\server\node_modules\ws\lib\Receiver.js:538:12)
 -------------------------------------------------------
[BATCH] Server Shutdown, waiting 15 seconds before a restart.

**Comment by CalvinDKHD** [comment]
I had the same problem, i updated the packet handler. From ItzLevvies version. And it was fixed!
