### ISSUE TITLE
Add Region error !

### ISSUE THREAD

**Issue by bobys16** [CigarProject/Cigar#315]
i try to add 2 new Region the server is running fine .
but i try to add new one / third region console is showing error .

this

events.js:72
throw er; // Unhandled 'error' event
^
Error: listen EADDRINUSE
at errnoException (net.js:901:11)
at Server._listen2 (net.js:1039:14)
at listen (net.js:1061:10)
at Server.listen (net.js:1135:5)
at GameServer.startStatsServer (/root/Cigar-oga/server/GameServer.js:1120:21)
at GameServer.start (/root/Cigar-oga/server/GameServer.js:292:10)
at MasterServer.createServer (/root/Cigar-oga/server/MasterServer.js:219:8)
at MasterServer.loadConfig (/root/Cigar-oga/server/MasterServer.js:141:22)
at MasterServer.start (/root/Cigar-oga/server/MasterServer.js:75:10)
at Object. (/root/Cigar-oga/server/index.js:55:18)

and this is my masterserver ini file 
serverIP = 51.254.157.61
serverPort = 80
gameserverPort = 1500
updateTime = 60
regions = {"A": 1, "FFA 1 - [Online]": 1, "FFA 2 - [Online]": 1}

Any helped will be appreciated :+1:

**Comment by darknight99x** [comment]
You need to into those other two region's gameserver.ini file and change the gameServerPort to something different for all 3.
